# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


report: "report/workflow.rst"


configfile: "config/config.yaml"


pepfile: config["pepfile"]


include: "rules/common.smk"
include: "rules/utils.smk"
include: "rules/MSA.smk"
include: "rules/phylogeny.smk"
include: "rules/ref.smk"


rule all:
    input:
        "results/test.txt",
