pepfile: config/pep/config.yaml

data-handling:
  # path of incoming data, which is moved to the
  # data directory by the preprocessing script
  data-query: data/query
  data-reference: data/reference

references-folder: resources/genomes

virus-reference-genome:
  - MN908947

# please comment/uncomment the regions you want to include in your analysis
# note, that there are two definitions for ORF1ab
regions-of-interest:
  - genome
  - ORF1ab
  - S
  - ORF3a
  - E
  - M
  - ORF6
  - ORF7a
  - ORF7b
  - ORF8
  - N
  - ORF10

