pepfile: config/pep/config.yaml

data-handling:
  # flag for using the following data-handling structure
  # True: data-handling structure is used as shown below
  # False: only the sample sheet needs to be updated (manually)
  use-data-handling: True
  # path of incoming data, which is moved to the
  # data directory by the preprocessing script
  incoming: ../MSA-input/

references-folder: resources/genomes

virus-reference-genome:
  - MN908947

references-of-interest:
  - B.1.640.1
  - B.1.640.2
