pepfile: config/pep/config.yaml

data-handling:
  # path of incoming data, which is moved to the
  # data directory by the preprocessing script
  data-query: data/query
  data-reference: data/reference

references-folder: resources/genomes

virus-reference-genome:
  - MN908947

regions-of-interest:
  - S
  - genome